version: '3.3'
services:
    mongo:
        image: mongo
    elasticsearch:
        environment:
            - http.host=0.0.0.0
            - 'ES_JAVA_OPTS=-Xms64m -Xmx128m'
        image: elasticsearch:7.7.1
    graylog:
        links:
            - mongo
            - elasticsearch
        ports:
            - '9000:9000'
            - '12201:12201'
            - '1514:1514'
        environment:
            - 'GRAYLOG_HTTP_EXTERNAL_URI=http://0.0.0.0:9000/'
        image: graylog
