version: '3'

services:
  influxdb:
    image: influxdb:latest
    deploy:
      replicas: 1
    environment:
      - "INFLUXDB_DB=homedb"
      - "INFLUXDB_HTTP_AUTH_ENABLED=true"
      - "INFLUXDB_ADMIN_USER=admin"
      - "INFLUXDB_ADMIN_PASSWORD=secretpassword"
    ports:
      - "8086:8086"
    volumes:
      - "influxdb:/var/lib/influxdb"
  kapacitor:
    image: kapacitor:latest
    deploy:
      replicas: 1
    environment:
      - "KAPACITOR_INFLUXDB_0_USERNAME=admin"
      - "KAPACITOR_INFLUXDB_0_PASSWORD=secretpassword"
      - "KAPACITOR_INFLUXDB_0_URLS_0=http://influxdb:8086"
    ports:
      - "9092:9092"
    volumes:
      - "kapacitor:/var/lib/kapacitor"
  chronograf:
    image: chronograf:latest
    deploy:
      replicas: 1
    ports:
      - "8888:8888"
    volumes:
      - "chronograf:/var/lib/chronograf"

volumes:
  influxdb:
  kapacitor:
  chronograf:
